# Generated by Django 2.1.7 on 2019-03-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(
                choices=[('Male', 'Male'), ('Female', 'Female')],
                max_length=6),
        ),
    ]
