# Generated by Django 2.2.1 on 2019-05-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190524_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture',
            new_name='image_url',
        ),
    ]
