# Generated by Django 2.2 on 2019-04-04 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('capacity', models.IntegerField()),
                ('location', models.TextField()),
                ('destination', models.TextField()),
                ('schedule', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2,
                                               max_digits=100)),
                ('type',
                 models.CharField(choices=[('local', 'local'),
                                           ('international', 'international')],
                                  max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
