# Generated by Django 2.2 on 2019-04-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flight',
            table='Flight',
        ),
    ]
