# Generated by Django 2.2 on 2019-04-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_admin'),
        ('flight', '0002_auto_20190404_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='createdBy',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='creator',
                to='users.User'),
        ),
        migrations.AddField(
            model_name='flight',
            name='updatedBy',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='updater',
                to='users.User'),
        ),
    ]
