# Generated by Django 2.2 on 2019-04-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20190404_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='createdBy',
            field=models.ForeignKey(
                db_column='createdBy',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='creator',
                to='users.User'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='updatedBy',
            field=models.ForeignKey(
                db_column='updatedBy',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='updater',
                to='users.User'),
        ),
    ]
