# Generated by Django 2.2 on 2019-04-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_auto_20190405_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='createdBy',
            field=models.ForeignKey(
                db_column='createdBy',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='createdBy',
                to='users.User'),
        ),
    ]
