# Generated by Django 2.2 on 2019-04-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_auto_20190406_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
