# Generated by Django 2.2 on 2019-04-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0011_auto_20190408_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='createdBy',
            field=models.ForeignKey(
                db_column='created_by',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='creator',
                to='users.User'),
        ),
    ]
