# Generated by Django 2.2 on 2019-04-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_auto_20190408_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='amount',
            new_name='currentPrice',
        ),
    ]
