# Generated by Django 2.2 on 2019-04-10 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0014_auto_20190408_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
