# Generated by Django 2.2.2 on 2019-06-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0016_auto_20190415_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='current_price',
            field=models.IntegerField(),
        ),
    ]
