# Generated by Django 2.2 on 2019-04-08 14:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0010_auto_20190408_1435'),
        ('users', '0006_auto_20190406_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(null=True)),
                ('cost', models.DecimalField(decimal_places=2,
                                             max_digits=100)),
                ('flight',
                 models.ForeignKey(db_column='flight_id',
                                   on_delete=django.db.models.deletion.CASCADE,
                                   related_name='flight',
                                   to='flight.Flight')),
                ('user',
                 models.ForeignKey(db_column='created_by',
                                   on_delete=django.db.models.deletion.CASCADE,
                                   related_name='user',
                                   to='users.User')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
