# Generated by Django 2.2 on 2019-04-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190408_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cost',
            new_name='ticket_price',
        ),
    ]
