# Generated by Django 2.2 on 2019-04-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190408_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='created_by',
        ),
    ]
