# Generated by Django 2.2 on 2019-04-09 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20190408_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expiryDate',
            field=models.DateTimeField(default=datetime.datetime(
                2019, 4, 9, 9, 24, 43, 708277, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
