# Generated by Django 2.2 on 2019-04-09 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20190409_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expiryDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
