# Generated by Django 2.2 on 2019-04-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20190409_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flight_id',
            field=models.ForeignKey(
                db_column='flight_id',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='flight',
                to='flight.Flight'),
        ),
    ]
