# Generated by Django 2.2 on 2019-04-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0014_auto_20190408_1510'),
        ('users', '0007_auto_20190408_1436'),
        ('booking', '0017_auto_20190409_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='_flight',
            new_name='flight_model',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('flight_model', 'created_by')},
        ),
    ]
