# Generated by Django 2.2 on 2019-04-10 04:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20190409_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(
                db_column='created_by',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='booked_by',
                to='users.User'),
        ),
    ]
