# Generated by Django 2.2.2 on 2019-06-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20190410_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_price',
            field=models.IntegerField(),
        ),
    ]
