# Generated by Django 2.2.2 on 2019-06-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_booking_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='paid',
        ),
    ]
