# Generated by Django 2.2.2 on 2019-07-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_remove_booking_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight_model',
            field=models.ForeignKey(
                db_column='flight_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='flight',
                to='flight.Flight'),
        ),
    ]
